# Generated by Django 4.0.4 on 2022-05-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('document', models.FileField(blank=True, upload_to='docs')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.CharField(max_length=255)),
                ('exp_years', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('exp_salary', models.CharField(max_length=255)),
                ('skillset', models.CharField(max_length=255)),
            ],
        ),
    ]
